# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://vigeoconsult.com
title: Vigeo Consulting
email: sales@vigeoconstruction.com
author: Joshua Coffie
description: > # "Write an awesome description for your new site here.
  Vigeo Consulting is a niche, boutique management consulting firm located in Denver, CO
  that specializes in management and technology advisory.
copyright: 'Copyright &copy; 2020 Vigeo Consulting. All Rights Reserved.'
credits: 'Vigeo Consulting is a subsidiary of <a href="http://vigeocorp.com">Vigeo Corp</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url:
